// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW5T85lilnvIcaZpVJ2WFFxHBKvtLx3M0',
    appId: '1:906107187459:web:65ac5d773a6bbbf6c23936',
    messagingSenderId: '906107187459',
    projectId: 'memento-60cce',
    authDomain: 'memento-60cce.firebaseapp.com',
    storageBucket: 'memento-60cce.firebasestorage.app',
    measurementId: 'G-LK67H0WDTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1EFILuQ2ZrcpJgiNIDTet52EZFWdiTr0',
    appId: '1:906107187459:android:998279fe07ea3e79c23936',
    messagingSenderId: '906107187459',
    projectId: 'memento-60cce',
    storageBucket: 'memento-60cce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmKk48oRUp1q8pnz2Vksra-K-bL2tdHw',
    appId: '1:906107187459:ios:3305573607aaca1ec23936',
    messagingSenderId: '906107187459',
    projectId: 'memento-60cce',
    storageBucket: 'memento-60cce.firebasestorage.app',
    androidClientId: '906107187459-t4j99pvoah71i0jkfrgn6p2fihdq3cfi.apps.googleusercontent.com',
    iosClientId: '906107187459-0l31iad4lc4ksunpa3t2r5elb2cji7fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.Memento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbmKk48oRUp1q8pnz2Vksra-K-bL2tdHw',
    appId: '1:906107187459:ios:3305573607aaca1ec23936',
    messagingSenderId: '906107187459',
    projectId: 'memento-60cce',
    storageBucket: 'memento-60cce.firebasestorage.app',
    androidClientId: '906107187459-t4j99pvoah71i0jkfrgn6p2fihdq3cfi.apps.googleusercontent.com',
    iosClientId: '906107187459-0l31iad4lc4ksunpa3t2r5elb2cji7fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.Memento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW5T85lilnvIcaZpVJ2WFFxHBKvtLx3M0',
    appId: '1:906107187459:web:a52626eda4a3bf6ec23936',
    messagingSenderId: '906107187459',
    projectId: 'memento-60cce',
    authDomain: 'memento-60cce.firebaseapp.com',
    storageBucket: 'memento-60cce.firebasestorage.app',
    measurementId: 'G-L8KXY11WL3',
  );
}
